version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:8
commands:
  setup_node_modules:
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - run: npm install
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  build:
    executor: default
    steps:
      - setup_node_modules
      - run: npm run typecheck
      - run: npm run lint
