name: Build

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install
        uses: actions/npm@master
        with:
          args: install
      - name: lint / test
        run: |
          npm run lint
          npm run test:type
          npm run test
