name: lint / test
on: [push]
jobs:
  test:
    name: run lint and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12]
    steps:
      - uses: actions/checkout@v1
      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run test:type
      - run: npm run test