name: lint / test
on: [push]
jobs:
  test:
    name: run lint / tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12]
    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install
        uses: actions/npm@master
        with:
          args: install
      - name: lint
        run: |
          npm run lint
          npm run test:type
          npm run test

