name: CI

on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: restore node_modules to/from cache
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node
      - name: install dependencies
        run: |
          npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - name: lint / typecheck / test
        run: |
          npm run lint
          npm run test:type
          npm run test
      - name: typecheck docs
        run: npm run docs:typecheck
      - uses: 8398a7/action-slack@v2.4.2
        with:
          status: ${{ job.status }}
          author_name: Type Checking
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
