name: CI

on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: restore node_modules to/from cache
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node
      - name: install dependencies
        run: |
          npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - name: lint / typecheck / test
        run: |
          npm run lint
          npm run test:type
          npm run test
