name: Release

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install
        uses: actions/npm@master
        with:
          args: install
      - name: tag
        uses: actions/bin/filter@master
        with:
          args: tag
      - name: publish
        uses: actions/npm@master
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          args: publish --access public