name: Release

on:
  push:
    branches:
      - master
    tags:
      - '!*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - name: restore node_modules to/from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node
      - name: install
        run: npm ci
      - name: check version and add tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPO: ${{github.repository}}
          COMMIT: ${{github.sha}}
        run: ./scripts/release.sh
      - name: build
        run: npm run build
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
